FROM node:22-alpine AS build
WORKDIR /src
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build


FROM nginx:1.25.4-alpine3.18
EXPOSE 4300

# Copy NGINX configurations
COPY ./eng/docker/nginx.conf /etc/nginx/nginx.conf
COPY ./eng/docker/nginx-default.conf /etc/nginx/conf.d/default.conf
COPY ./eng/docker/nginx-start.sh .

# Copy website
COPY --from=build /src/dist/sbus-emulator-frontend/browser /usr/share/nginx/html

ENTRYPOINT ["sh", "nginx-start.sh"]
