# File: .github/workflows/docker-publish.yml
name: Build and Publish Docker image

on:
  push:
    branches:
      - main
      
permissions:
  contents: read
  packages: write
  id-token: write  # necessário para login com GITHUB_TOKEN no ghcr

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Definir IMAGE_TAG sem barras
        run: |
          # GITHUB_REF_NAME já é só o nome da branch (sem refs/heads/)
          TAG="${GITHUB_REF_NAME//\//-}"
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV        

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image (Frontend)
        run: |
          docker build \
            --file ./frontend/eng/docker/dockerfile \
            --tag ghcr.io/${{ github.repository }}/blogdoft-sbus-client:${{ github.sha }} \
            --tag ghcr.io/${{ github.repository }}/blogdoft-sbus-client:${IMAGE_TAG} \
            --tag ghcr.io/${{ github.repository }}/blogdoft-sbus-client:latest \
            ./frontend/

      - name: Push image to GHCR (Frontend)
        run: |
          docker push ghcr.io/${{ github.repository }}/blogdoft-sbus-client:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/blogdoft-sbus-client:latest

      - name: Build Docker image (Backend)
        run: |
          docker build \
            --file ./backend/eng/docker/dockerfile \
            --tag ghcr.io/${{ github.repository }}/blogdoft-sbus-api:${{ github.sha }} \
            --tag ghcr.io/${{ github.repository }}/blogdoft-sbus-api:${IMAGE_TAG} \
            --tag ghcr.io/${{ github.repository }}/blogdoft-sbus-api:latest \
            ./backend/

      - name: Push image to GHCR (Backend)
        run: |
          docker push ghcr.io/${{ github.repository }}/blogdoft-sbus-api:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/blogdoft-sbus-api:latest
